Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -32,4 +32,15 @@ jobs:
       - uses: fastai/workflows/nbdev-ci@master
         with:
           version: ${{ matrix.version }}
+      - name: test build docs
+        run: |
+          make prepare
+          if [ -f "mkdocs/site/index.html" ]; then
+            echo "docs built successfully."
+          else
+            echo "index page not found in rendered docs."
+            ls -la
+            ls -la mkdocs/site/
+            exit 1
+          fi
 
